@host=https://localhost:7215
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyNDE2NzBhYi02ZGVkLTRlYzItOGEwYy02NTVmMGU3NjE1ZmEiLCJnaXZlbl9uYW1lIjoiSm9zw6kiLCJmYW1pbHlfbmFtZSI6Ikdpcm9uIiwianRpIjoiNWFhM2ZlNjktMTU4OS00OTgxLTkzYTItMzRhOTEyYTkwZWJmIiwiZXhwIjoxNjc4Mzg3OTU3LCJpc3MiOiJIYWhuIiwiYXVkIjoiSGFobiJ9.W-9h_Bm6jHrQdtxH9jb9IbFC7cb-c45xjrLilz8kRIM

POST {{host}}/orders
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "CustomerName": "Test",
    "OrderDate": "2019-01-01",
    "TotalAmount": 1000
}