@host=https://localhost:7215
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZTk1MWUzNy05NTk0LTQ0MjItOGNjNy1kMDlkZTAwZWQyZGMiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwianRpIjoiODA0OTU0OTQtYTYzYi00NTc2LTlmMzMtMGI5ZDJmZThjNWUzIiwiZXhwIjoxNjc4Mzk5NTc2LCJpc3MiOiJIYWhuIiwiYXVkIjoiSGFobiJ9.ZvGkuGy9Gx8jVaPdM-y-aDllXreAA5Smkgtm93tqyMw

POST {{host}}/orders
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "CustomerName": "Test",
    "OrderDate": "2019-01-01",
    "TotalAmount": 1000
}