@host=https://localhost:7215
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZTk1MWUzNy05NTk0LTQ0MjItOGNjNy1kMDlkZTAwZWQyZGMiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwianRpIjoiMWNmMDI1OWYtNzE2My00Mjk0LTg5ZTYtMTUyMWMzMDg2M2NmIiwiZXhwIjoxNjc4MzQzNzEyLCJpc3MiOiJIYWhuIiwiYXVkIjoiSGFobiJ9.syRfiD61udquSDHCWy-oP8rLe0k-jtgAN-0p7_9qxOg

GET {{host}}/orders
Content-Type: application/json
Authorization: Bearer {{token}}